#pragma config(Motor,  port2,           frontRightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           intakeLeft,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeRight,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           backLeftMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           backRightMotor,  tmotorServoContinuousRotation, openLoop)
#pragma DebuggerWindows("debugStream")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++


const int fastSensitivity = 2;
//Main Driving Loop
task driveLoop(){
	while(1 == 1)
	  {
	    motor[frontRightMotor] = vexRT[Ch2];
	    motor[frontLeftMotor] = vexRT[Ch3];
	    motor[backRightMotor] = vexRT[Ch2];
	    motor[backLeftMotor] = vexRT[Ch3];
	    writeDebugStream("RIGHT: %d\nLEFT: %d\n",vexRT[Ch2],vexRT[Ch3]);
		
	    EndTimeSlice();
	  }
}

//Drive Fast
task fastDriveLoop(){
	while(1==1){


		motor[frontRightMotor] = (255- (vexRT[Ch1]/fastSensitivity));
		motor[frontLeftMotor] = (255 + (vexRT[Ch1]/fastSensitivity));
		motor[backRightMotor] = (255- (vexRT[Ch1]/fastSensitivity));
		motor[backLeftMotor] = (255 + (vexRT[Ch1]/fastSensitivity));
		writeDebugStream("RIGHT: %d\nLEFT: %d\n",(255-vexRT[Ch1]/fastSensitivity),(255+vexRT[Ch1]/fastSensitivity));
		EndTimeSlice();
	}
}

task main()
{
  startTask(driveLoop);
  while(1==1){

  //Accelerate
	 	if(vexRT[Btn6D] == 1){
	 		stopTask(driveLoop);
	 		startTask(fastDriveLoop);
	 	}
	 	else{
	 		stopTask(fastDriveLoop);
	 		startTask(driveLoop);
	 	}


	 	//Intake Motors
 	 if(vexRT[Btn5U] == 1){
 		motor[intakeLeft] = 80;
 		motor[intakeRight] = 80;
	 	}
	 	else{
	 		motor[intakeLeft] = 0;
	 		motor[intakeRight] = 0;
	 	}


	 	EndTimeSlice();
	}

}




//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
