#pragma config(Motor,  port2,           rightMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           intakeLeft,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           intakeRight,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           outtakeLeft,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           outtakeRight,  tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

//Main Driving Loop
task driveLoop(){
	while(1 == 1)
	  {
	    motor[rightMotor] = vexRT[Ch2];
	    motor[leftMotor] = vexRT[Ch3];
	    EndTimeSlice();
	  }
}

//Drive Fast
task fastDriveLoop(){
	while(1==1){


		motor[rightMotor] = (150 + vexRT[Ch1]);
		motor[leftMotor] = (100 - vexRT[Ch1]);
		EndTimeSlice();
	}
}

task main()
{
  startTask(fastDriveLoop);
  while(1==1){

  //Accelerate
	 	if(vexRT[Btn6D] == 1){
	 		stopTask(driveLoop);
	 		startTask(fastDriveLoop);
	 	}
	 	else{
	 		stopTask(fastDriveLoop);
	 		startTask(driveLoop);
	 	}


	 	//Intake Motors
 	 if(vexRT[Btn5U] == 1){
 		motor[intakeLeft] = 255;
 		motor[intakeRight] = 255;
	 	}
	 	else{
	 		motor[intakeLeft] = 0;
	 		motor[intakeRight] = 0;
	 	}


	 	//Outtake Motors
	 	if(vexRT[Btn5D] == 1){
 		motor[outtakeLeft] = 255;
 		motor[outtakeRight] = 255;
	 	}
	 	else{
	 		motor[outtakeLeft] = 0;
	 		motor[outtakeRight] = 0;
	 	}


	 	EndTimeSlice();
	}

}




//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
